# Generated by Django 2.2.12 on 2021-09-02 08:16

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=3000)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=255, unique=True)),
                ('depth', models.PositiveIntegerField()),
                ('numchild', models.PositiveIntegerField(default=0)),
                ('name', models.CharField(blank=True, default='', max_length=3000)),
            ],
        ),
        migrations.CreateModel(
            name='Desk',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=3000)),
            ],
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_datetime', models.DateTimeField(blank=True, default=django.utils.timezone.now, verbose_name='date of document creation')),
                ('filename', models.CharField(max_length=1000)),
                ('brand', models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.CASCADE, to='exampleapp.Brand')),
            ],
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=3000)),
                ('parent', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='exampleapp.Topic')),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=3000)),
                ('parent', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='exampleapp.Region')),
            ],
        ),
        migrations.CreateModel(
            name='Evaluation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exampleapp.Document')),
            ],
        ),
        migrations.CreateModel(
            name='Documenttopics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exampleapp.Document')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exampleapp.Topic')),
            ],
            options={
                'unique_together': {('document', 'topic')},
            },
        ),
        migrations.CreateModel(
            name='Documentregions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exampleapp.Document')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exampleapp.Region')),
            ],
            options={
                'unique_together': {('document', 'region')},
            },
        ),
        migrations.CreateModel(
            name='Documentcategories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exampleapp.Category')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exampleapp.Document')),
            ],
            options={
                'unique_together': {('document', 'category')},
            },
        ),
        migrations.AddField(
            model_name='document',
            name='categories',
            field=models.ManyToManyField(through='exampleapp.Documentcategories', to='exampleapp.Category'),
        ),
        migrations.AddField(
            model_name='document',
            name='desk',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='exampleapp.Desk'),
        ),
        migrations.AddField(
            model_name='document',
            name='regions',
            field=models.ManyToManyField(through='exampleapp.Documentregions', to='exampleapp.Region'),
        ),
        migrations.AddField(
            model_name='document',
            name='topics',
            field=models.ManyToManyField(through='exampleapp.Documenttopics', to='exampleapp.Topic'),
        ),
    ]
