# Generated by Django 3.2.7 on 2021-10-01 07:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    replaces = [('flex_abac', '0002_basefilter_name'), ('flex_abac', '0003_auto_20210909_1058'), ('flex_abac', '0004_auto_20210910_1218'), ('flex_abac', '0005_auto_20210915_0712'), ('flex_abac', '0006_alter_role_name'), ('flex_abac', '0007_alter_policy_name'), ('flex_abac', '0008_auto_20210928_1700'), ('flex_abac', '0009_auto_20210928_1702'), ('flex_abac', '0010_auto_20210929_1015'), ('flex_abac', '0011_auto_20210930_1235')]

    dependencies = [
        ('flex_abac', '0001_initial'),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='basefilter',
            name='name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='action',
            name='pretty_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='userrole',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='modelcategoricalattribute',
            unique_together={('attribute_type', 'owner_content_type')},
        ),
        migrations.AlterUniqueTogether(
            name='modelgenericattribute',
            unique_together={('attribute_type', 'owner_content_type')},
        ),
        migrations.AlterUniqueTogether(
            name='modelmaterializednestedcategoricalattribute',
            unique_together={('attribute_type', 'owner_content_type')},
        ),
        migrations.AlterUniqueTogether(
            name='modelnestedcategoricalattribute',
            unique_together={('attribute_type', 'owner_content_type')},
        ),
        migrations.AlterField(
            model_name='role',
            name='name',
            field=models.CharField(max_length=512, unique=True),
        ),
        migrations.AlterField(
            model_name='policy',
            name='name',
            field=models.CharField(max_length=512, unique=True),
        ),
        migrations.AlterModelOptions(
            name='categoricalfilter',
            options={},
        ),
        migrations.AlterUniqueTogether(
            name='categoricalfilter',
            unique_together={('value', 'attribute_type')},
        ),
        migrations.AlterModelOptions(
            name='genericfilter',
            options={},
        ),
        migrations.AlterModelOptions(
            name='nestedcategoricalfilter',
            options={},
        ),
        migrations.AlterUniqueTogether(
            name='genericfilter',
            unique_together={('value', 'attribute_type')},
        ),
        migrations.AlterUniqueTogether(
            name='materializednestedcategoricalfilter',
            unique_together={('value', 'attribute_type')},
        ),
        migrations.AlterUniqueTogether(
            name='nestedcategoricalfilter',
            unique_together={('value', 'attribute_type')},
        ),
        migrations.AlterModelOptions(
            name='categoricalfilter',
            options={'base_manager_name': 'objects'},
        ),
        migrations.AlterUniqueTogether(
            name='categoricalfilter',
            unique_together=set(),
        ),
        migrations.AlterModelOptions(
            name='categoricalfilter',
            options={},
        ),
        migrations.AlterUniqueTogether(
            name='categoricalfilter',
            unique_together={('attribute_type', 'value')},
        ),
    ]
